server:
  host: 0.0.0.0
  port: 8080


database:
  dsn: "postgres://postgres:postgres@db:5432/warehouse?sslmode=disable"
  host: db
  port: 5432
  user: postgres
  password: 12345678
  name: warehouse
  sslmode: disable

jwt_secret: andrey